var gulp = require('gulp');
require('./gulp/path');
require('./gulp/clean');
require('./gulp/sass');
require('./gulp/javascript');
require('./gulp/html');
require('./gulp/resources');
require('./gulp/libs');
require('./gulp/watch');
require('./gulp/build');